{% set name = "ophyd-async" %}
{% set version = "0.14.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ophyd_async-{{ version }}.tar.gz
  sha256: 800bf6cdafd6318de3cd51c47791a924b9189aff2ced057b0443e67576fa455f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - bluesky-base >=1.13.1rc2
    - event-model >=1.23
    - pyyaml
    - colorlog
    - pydantic >=2.0
    - pydantic-numpy
    - stamina >=23.1.0
    - scanspec >=0.8
    - velocity-profile
    - h5py
    - aioca >=2.0
    - p4p >=4.2.0
    - pytango >=10.0.2

test:
  imports:
    - ophyd_async
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://blueskyproject.io/ophyd-async
  summary: Asynchronous Bluesky hardware abstraction code, compatible with control systems like EPICS and Tango
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thopkins32
    - mrakitin
    - jwlodek
